//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteDeiPeschi.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento numConto dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo", ReplyAction="*")]
        MonteDeiPeschi.ServiceReference1.SaldoResponse Saldo(MonteDeiPeschi.ServiceReference1.SaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo", ReplyAction="*")]
        System.Threading.Tasks.Task<MonteDeiPeschi.ServiceReference1.SaldoResponse> SaldoAsync(MonteDeiPeschi.ServiceReference1.SaldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saldo", Namespace="http://tempuri.org/", Order=0)]
        public MonteDeiPeschi.ServiceReference1.SaldoRequestBody Body;
        
        public SaldoRequest() {
        }
        
        public SaldoRequest(MonteDeiPeschi.ServiceReference1.SaldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numConto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codiceFiscale;
        
        public SaldoRequestBody() {
        }
        
        public SaldoRequestBody(string numConto, string codiceFiscale) {
            this.numConto = numConto;
            this.codiceFiscale = codiceFiscale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaldoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MonteDeiPeschi.ServiceReference1.SaldoResponseBody Body;
        
        public SaldoResponse() {
        }
        
        public SaldoResponse(MonteDeiPeschi.ServiceReference1.SaldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal SaldoResult;
        
        public SaldoResponseBody() {
        }
        
        public SaldoResponseBody(decimal SaldoResult) {
            this.SaldoResult = SaldoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MonteDeiPeschi.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MonteDeiPeschi.ServiceReference1.WebService1Soap>, MonteDeiPeschi.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MonteDeiPeschi.ServiceReference1.SaldoResponse MonteDeiPeschi.ServiceReference1.WebService1Soap.Saldo(MonteDeiPeschi.ServiceReference1.SaldoRequest request) {
            return base.Channel.Saldo(request);
        }
        
        public decimal Saldo(string numConto, string codiceFiscale) {
            MonteDeiPeschi.ServiceReference1.SaldoRequest inValue = new MonteDeiPeschi.ServiceReference1.SaldoRequest();
            inValue.Body = new MonteDeiPeschi.ServiceReference1.SaldoRequestBody();
            inValue.Body.numConto = numConto;
            inValue.Body.codiceFiscale = codiceFiscale;
            MonteDeiPeschi.ServiceReference1.SaldoResponse retVal = ((MonteDeiPeschi.ServiceReference1.WebService1Soap)(this)).Saldo(inValue);
            return retVal.Body.SaldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MonteDeiPeschi.ServiceReference1.SaldoResponse> MonteDeiPeschi.ServiceReference1.WebService1Soap.SaldoAsync(MonteDeiPeschi.ServiceReference1.SaldoRequest request) {
            return base.Channel.SaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MonteDeiPeschi.ServiceReference1.SaldoResponse> SaldoAsync(string numConto, string codiceFiscale) {
            MonteDeiPeschi.ServiceReference1.SaldoRequest inValue = new MonteDeiPeschi.ServiceReference1.SaldoRequest();
            inValue.Body = new MonteDeiPeschi.ServiceReference1.SaldoRequestBody();
            inValue.Body.numConto = numConto;
            inValue.Body.codiceFiscale = codiceFiscale;
            return ((MonteDeiPeschi.ServiceReference1.WebService1Soap)(this)).SaldoAsync(inValue);
        }
    }
}
